baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Aryan Gupta'
[taxonomies]
    tags = "tags"
    categories = "categories"

pygmentsUseClasses=true
pygmentsCodeFences=true
googleAnalytics="G-4RVTZ5FQQF"
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Blog Posts"
    url = "/posts/"
    weight = 2
    [[menu.main]]
    weight = 3
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    [[menu.main]]
    weight = 4
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/#About"
    title = ""
  
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false 
    startLevel = 2